### ISSUE TITLE
Words input glitches sometimes

### ISSUE THREAD

**Issue by vgrebenschikov** [vgrebenschikov/thehat#42]
Button highlighted back and forth 
Plus button overlaps with words

**Comment by ushakov** [comment]
Which button overlaps?
(Highlight is some material-ui magic, probably lower priority)

**Comment by ushakov** [comment]
![photo5262776612548619784](https://user-images.githubusercontent.com/38851/80078575-c6ab8580-8557-11ea-8477-7b267601d3fb.jpg)

**Comment by ushakov** [comment]
Partially fixed by #48 . Please let me know if there is more I can do.
