### ISSUE TITLE
Support players icons from google

### ISSUE THREAD

**Issue by vgrebenschikov** [vgrebenschikov/thehat#52]
Google besides authentication can provide ppl icons, it would be great to support them in our UI

Places to show user icon:

 - [x] list of users in drawer
 - [ ] explanation header who -> whom
 - [ ] results table

**Comment by ushakov** [comment]
I believe we already show the picture in top right corner. Where else
should we show it?

**Comment by vgrebenschikov** [comment]
Places to show user icon:
- list of users in drawer 
- explanation header who -> whom 
- results table

**Comment by ushakov** [comment]
closed by #59
