### ISSUE TITLE
Игра внезапно начинается, до того как все желающие к ней подсоединились 

### ISSUE THREAD

**Issue by nkolodkina** [vgrebenschikov/thehat#84]
Кейс: Все, кто зашли, уже написали слова, игра внезапно началась. При этом есть пара человек, которые не успели зайти и начать писать слова, они уже никак не могут присоединиться. Пришлось заново писать слова.

Можно явно спрашивать подтверждение для начала игры. Или разрешать присоединяться к игре, пока не начали объяснять слова.

**Comment by vgrebenschikov** [comment]
Давайте не авто-стартовать игру по добавлении всех слов
